baseURL = "https://nvandal.github.io"
languageCode = "en-us"
title = "nvandal blog"
theme = "ananke"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.menu]]
  name = "blog"
  url = "post/"

